{% set name = "in-silico-fate-mapping" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6e0c36098bd7afbc245934af492afd501040b16e1df5e09b270ef38879c4bb37

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - div = in_silico_fate_mapping.cli.divergence_cli:div

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - click
    - magicgui
    - napari
    - numpy
    - pandas
    - python >=3.8
    - scikit-learn
    - qtpy
    - zarr

test:
  imports:
    - in_silico_fate_mapping
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/royerlab/in-silico-fate-mapping
  summary: Interactive in silico fate mapping from tracking data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - JoOkuma
