{% set name = "in-silico-fate-mapping" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/in-silico-fate-mapping-{{ version }}.tar.gz
  sha256: 57782845a88c05bed888d53dd2a2cd6dd940001e8c3745297c4a9dd8a8931a68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - div = in_silico_fate_mapping.cli.divergence_cli:div

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - click
    - magicgui
    - napari
    - numpy
    - pandas
    - python >=3.8
    - scikit-learn
    - qtpy
    - zarr

test:
  imports:
    - in_silico_fate_mapping
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/royerlab/in-silico-fate-mapping
  summary: Interactive in silico fate mapping from tracking data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - JoOkuma
